# Generated by Django 5.2.4 on 2025-07-27 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('email', 'Email Phishing'), ('sms', 'SMS Spam'), ('url', 'URL Malicious')], max_length=10)),
                ('input_text', models.TextField()),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
